alter table products
    add column new_id bigint generated by default as identity;

update products
set new_id = id;

select nextval('products_id_seq');

select nextval(
               pg_get_serial_sequence('products', 'new_id')
       );


select setval(
               pg_get_serial_sequence('products', 'new_id'),
               (select max(id) from products)
       );

alter table products
drop
constraint if exists products_pkey;


alter table products
drop
column id;


alter table products
    rename column new_id to id;


alter table products
    alter column id set generated always;

alter table products
    add constraint products_pkey primary key (id);

drop sequence if exists products_id_seq;
